export { default as Games } from './game';
export { default as Player } from './player';
export { default as Communities } from './communities';
export { default as Open } from './open';
export { default as Close } from './close';
export { default as CopyRight } from './copyRight';
export { default as Star } from './star';
export { default as HeaderArrow } from './HeaderArrow';
export { default as RightArrow } from './RightArrow';